Feature/layout
Aleksey-Bortnik/Productly-layout pull request #6
Opened 2021-07-07 10:00 UTC by Aleksey-Bortnik

new branch naming, with latest fix.

2021-07-07 10:56 UTC, irina-chernik requested changes

2021-07-07 10:56 UTC, irina-chernik commented on scss/components/_banner.scss
> +    width: 179px;
don't use fixed height/width

2021-07-07 10:56 UTC, irina-chernik commented on scss/components/_tools.scss
> +    width: 50px;
use one common class for repeting styles - width and height

2021-07-07 10:56 UTC, irina-chernik commented on scss/components/_strategies.scss
> +  &__card{
add space

2021-07-07 10:56 UTC, irina-chernik commented on scss/components/_design.scss
> +  font-size: 1em;
indent

2021-07-07 14:40 UTC, irina-chernik approved these changes

2021-07-08 07:58 UTC, angelinabylitskaya commented on gulpfile.js
> +const gulp = require("gulp");
Mixed quotes in one file. Use only one quotes style. Fix to single quotes.

2021-07-08 07:58 UTC, angelinabylitskaya commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
Add some scripts to build and watch SCSS compilation. If you have scripts, you Donn't need to remember all CLI commands.

2021-07-08 07:58 UTC, angelinabylitskaya commented on index.html
>  </html>
Empty line at the end is missing

2021-07-08 07:58 UTC, angelinabylitskaya commented on scss/base/_common_classes.scss
> +.primary-title {
Well done!
You can separate layout classes and typography classes in corresponding files.

2021-07-08 11:52 UTC, merged